version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - 'dependencies'
    rebase-strategy: disabled
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    rebase-strategy: disabled
    groups:
      gradle-plugins:
        patterns:
          - "io.github.gradle-nexus.publish-plugin*"
          - "com.diffplug.spotless*"
      gradle-dependencies:
        patterns:
          - "*"
