services:
  package:
    image: azul/zulu-openjdk:8-latest
    tty: true
    stdin_open: true
    working_dir: /home/package
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
    depends_on:
      - meilisearch
    links:
      - meilisearch
    volumes:
      - ./:/home/package

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
