/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meilisearch;

import meilisearch.model.Index;
import org.junit.Before;
import org.junit.Test;


public class IndexesTest {

    MSClient ms;

    @Before
    public void initialize() {
        ms = new MSClient(new Config("http://localhost:7700", ""));
    }

    @Test
    public void createIndex() throws Exception {
        String name = "Movies";
        Schema schema = new Schema(
                new String[]{ "identifier", "indexed", "displayed" },
                new String[]{ "indexed", "displayed" },
                new String[]{ "indexed", "displayed" },
                new String[]{ "displayed" },
                new String[]{ "displayed" }
        );

        System.out.println(ms.createIndex(name, schema));
    }

    @Test
    public void getIndexes() throws Exception {
        Index[] indexes = ms.getIndexes();
        for (int a = 0; a < indexes.length; a++) {
            System.out.println(indexes[a].getUid());
        }

    }

    @Test
    public void getIndex() throws Exception {
        // TODO: input uid for test
        Index index = ms.getIndex("4ayjgirl");
        System.out.println(index.getUid());
    }

    @Test
    public void put() throws Exception {

    }

    @Test
    public void delete() throws Exception {

    }
}
