/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meilisearch;

import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import static org.junit.Assert.*;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class IndexesTest {
	private static final String indexUid = "__TEST_VIDEOS";
	static MeilisearchClient ms = new MeilisearchClient(new MeilisearchConfig("http://localhost:7700"));

	private static int initialIndexCount = 0;

	@BeforeClass
	public static void getIndexesBeforeTest() throws Exception {
		initialIndexCount = ms.getIndexList().length;
	}

	@Test
	public void test1_shouldCreateIndex() throws Exception {
		assertNotEquals("", ms.createIndex(indexUid));
	}

	@Test
	public void test2_clientShouldHaveExactlyOneIndex() throws Exception {
		MeilisearchIndex[] meilisearchIndexes = ms.getIndexList();
		assertEquals(initialIndexCount + 1, meilisearchIndexes.length);
	}

	@Test
	public void test3_shouldGetIndex() throws Exception {
		MeilisearchIndex testIndex = ms.getIndex(indexUid);
		assertNotNull(testIndex);
	}

	@Test
	public void test4_shouldDeleteIndex() throws Exception {
		ms.deleteIndex(indexUid);
		assertEquals(initialIndexCount, ms.getIndexList().length);
	}
}
