/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meilisearch;

import org.junit.Before;
import org.junit.Test;


public class MeiliSearchTest {

    MSClient ms;

    @Before
    public void initialize() {
        ms = new MSClient(new Config("http://localhost:7700", ""));
    }

    @Test
    public void createIndex() throws Exception {
        String name = "Movies";
        Schema schema = new Schema(
                new String[]{ "identifier", "indexed", "displayed" },
                new String[]{ "indexed", "displayed" },
                new String[]{ "indexed", "displayed" },
                new String[]{ "displayed" },
                new String[]{ "displayed" }
        );

        System.out.println(ms.createIndex(name, schema));
    }

    @Test
    public void getIndexes() throws Exception {
        System.out.println(ms.getIndexes());
    }

    @Test
    public void getIndex() throws Exception {
        System.out.println(ms.getIndex("4ayjgirl"));
    }
}
