version: "3.8"

services:
  package:
    image: mcr.microsoft.com/devcontainers/java:8
    tty: true
    stdin_open: true
    working_dir: /workspace
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
    depends_on:
      - meilisearch
    links:
      - meilisearch
    volumes:
      - ../:/workspace

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
